import jsPDF from 'jspdf'
import logoTitle from '../assets/logo_title.png'

export function exportPlanPdf(
    plan,
    taskBreakdowns = {}
) {
    const pdf =
        new jsPDF()

    let pageNumber = 1

    const drawPageBackground =
        () => {
            pdf.setFillColor(
                2,
                6,
                23
            )

            pdf.rect(
                0,
                0,
                210,
                297,
                'F'
            )

            pdf.addImage(
                logoTitle,
                'PNG',
                20,
                10,
                55,
                18
            )

            pdf.setFillColor(
                139,
                92,
                246
            )

            pdf.rect(
                20,
                34,
                70,
                2,
                'F'
            )

            pdf.setTextColor(
                255,
                255,
                255
            )

            pdf.setFontSize(18)

            pdf.text(
                `${plan.plan_type.toUpperCase()} PLAN`,
                20,
                48
            )

            pdf.setTextColor(
                100,
                116,
                139
            )

            pdf.setFontSize(10)

            pdf.text(
                `Generated on ${new Date().toLocaleDateString()}`,
                20,
                56
            )
        }

    const drawFooter =
        () => {
            pdf.setTextColor(
                100,
                116,
                139
            )

            pdf.setFontSize(9)

            pdf.text(
                'Generated by AiStraX',
                20,
                288
            )

            pdf.text(
                `Page ${pageNumber}`,
                180,
                288
            )
        }

    function ensureSpace(
        neededHeight
    ) {
        if (
            y + neededHeight > 260
        ) {
            drawFooter()

            pdf.addPage()

            pageNumber++

            drawPageBackground()

            y = 75
        }
    }

    drawPageBackground()

    let y = 75

    plan.tasks.forEach(
        (
            task,
            index
        ) => {
            const breakdown =
                taskBreakdowns?.[
                    index
                    ] || []

            const taskLines =
                pdf.splitTextToSize(
                    task.name,
                    140
                )

            const cardHeight =
                Math.max(
                    34,
                    22 +
                    taskLines.length * 8
                )

            const breakdownHeight =
                breakdown.reduce(
                    (
                        total,
                        step
                    ) => {
                        const stepLines =
                            pdf.splitTextToSize(
                                step.title,
                                120
                            )

                        return (
                            total +
                            Math.max(
                                12,
                                stepLines.length * 6
                            )
                        )
                    },
                    0
                )

            const blockHeight =
                cardHeight +
                20 +
                breakdownHeight

            ensureSpace(
                blockHeight
            )

            pdf.setFillColor(
                30,
                41,
                59
            )

            pdf.roundedRect(
                15,
                y,
                180,
                cardHeight,
                4,
                4,
                'F'
            )

            pdf.setFillColor(
                139,
                92,
                246
            )

            pdf.circle(
                25,
                y + 11,
                5,
                'F'
            )

            pdf.setTextColor(
                255,
                255,
                255
            )

            pdf.setFontSize(9)

            pdf.text(
                String(index + 1),
                23.5,
                y + 12.5
            )

            pdf.setFontSize(12)

            pdf.text(
                taskLines,
                35,
                y + 10
            )

            let priorityLabel =
                'Low'

            let r = 34
            let g = 197
            let b = 94

            if (
                task.priority === 1
            ) {
                priorityLabel =
                    'High'

                r = 239
                g = 68
                b = 68
            }

            if (
                task.priority === 2
            ) {
                priorityLabel =
                    'Medium'

                r = 245
                g = 158
                b = 11
            }

            pdf.setTextColor(
                r,
                g,
                b
            )

            pdf.setFontSize(10)

            pdf.text(
                `Priority: ${priorityLabel}`,
                35,
                y + 18 +
                taskLines.length * 8
            )

            if (
                task.assigned_to
            ) {
                pdf.setTextColor(
                    56,
                    189,
                    248
                )

                pdf.text(
                    `Assigned: ${task.assigned_to}`,
                    95,
                    y + 18 +
                    taskLines.length * 8
                )
            }

            y +=
                cardHeight + 10

            if (
                breakdown.length > 0
            ) {
                pdf.setTextColor(
                    139,
                    92,
                    246
                )

                pdf.setFontSize(11)

                pdf.text(
                    'Detailed Breakdown',
                    20,
                    y
                )

                y += 10

                breakdown.forEach(
                    (
                        step,
                        stepIndex
                    ) => {
                        const stepLines =
                            pdf.splitTextToSize(
                                step.title,
                                120
                            )

                        const stepHeight =
                            Math.max(
                                12,
                                stepLines.length * 6
                            )

                        ensureSpace(
                            stepHeight + 10
                        )

                        pdf.setTextColor(
                            255,
                            255,
                            255
                        )

                        pdf.setFontSize(10)

                        let globalDay = 1

                        for (
                            let i = 0;
                            i < index;
                            i++
                        ) {
                            if (
                                taskBreakdowns[i]
                            ) {
                                globalDay +=
                                    taskBreakdowns[i].length
                            }
                        }

                        const dayLabel =
                            `Day ${
                                globalDay +
                                stepIndex
                            }`

                        pdf.text(
                            dayLabel,
                            25,
                            y
                        )

                        pdf.setTextColor(
                            203,
                            213,
                            225
                        )

                        pdf.text(
                            stepLines,
                            55,
                            y
                        )

                        y += stepHeight
                    }
                )

                y += 10
            }
        }
    )

    drawFooter()

    pdf.save(
        `${plan.plan_type}-plan.pdf`
    )
}